-- Migration: Seed the 43-tour catalog
-- Auto-generated from src/data/tours.ts by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Re-run `node scripts/generate-seed-sql.mjs` after changing the catalog in code.

insert into tours (name, description, category, price_per_person, flat_rate, flat_rate_amount, tour_type, group_minimum_size, max_capacity, includes_meals)
values
  ('Catamaran Cruise', 'Sail on crystal clear waters', 'Water', 110, false, null, 'standard', 1, null, true),
  ('Dunn''s River & Blue Hole', 'Twin waterfall experience with natural swimming pools', 'Adventure', 120, false, null, 'standard', 4, null, true),
  ('Dunn''s River Falls Only', 'Iconic cascading waterfalls with limestone terraces', 'Nature', 87.5, false, null, 'standard', 1, null, false),
  ('Blue Hole Only', 'Cenote swimming in lush jungle surroundings', 'Adventure', 90, false, null, 'standard', 4, null, false),
  ('ATV, Zipline, Horseback, Catamaran & Jeep Safari', 'High-octane adventure through mountains and forests', 'Extreme', 165, false, null, 'standard', 1, null, true),
  ('ATV, Zipline, Horseback & Rick''s Cafe Negril', 'Adventure and dining experience in Negril', 'Extreme', 189, false, null, 'standard', 1, null, true),
  ('ATV & Zipline', 'Combine two thrilling activities', 'Extreme', 169, false, null, 'standard', 1, null, false),
  ('ATV & Horseback', 'Off-road adventure combined with horseback riding', 'Extreme', 169, false, null, 'standard', 1, null, false),
  ('Eco Adventure Park', 'Dune buggy, zipline, river rafting, tubing, e-bike', 'Adventure', 209, false, null, 'standard', 1, null, false),
  ('Luminous Lagoon', 'Swim in glowing bioluminescent waters at night', 'Nature', 55, false, null, 'standard', 1, null, false),
  ('Bamboo Rafting, Great River', 'Scenic bamboo raft with limestone massage', 'Relaxation', 70, false, null, 'standard', 1, null, false),
  ('Martha Brae Rafting', 'Scenic bamboo raft journey down historic river', 'Relaxation', 90, false, null, 'standard', 1, null, false),
  ('River Tubing', 'Thrilling tubing adventure down tropical river', 'Adventure', 55, false, null, 'standard', 1, null, false),
  ('Negril Day Tour, Shopping & Rick''s Cafe', 'Beach, shopping, and dining experience', 'Combined', 60, false, null, 'standard', 1, null, false),
  ('ATV Only', 'Solo all-terrain vehicle adventure', 'Extreme', 140, false, null, 'standard', 1, null, false),
  ('Clear Kayak', 'Glass kayak for viewing coral reefs and marine life', 'Water', 180, false, null, 'standard', 1, null, false),
  ('Jet Car', 'High-speed jet car adventure — priced per vehicle, not per person', 'Extreme', 250, false, null, 'standard', 1, null, false),
  ('Jet Ski', 'Fast-paced water adventure', 'Water', 100, false, null, 'standard', 4, null, false),
  ('Nightlife', 'Experience Jamaica''s vibrant nightlife', 'Entertainment', 25, false, null, 'standard', 4, null, false),
  ('Private Yacht Charter', 'Luxury 3-hour yacht charter for up to 18 guests, including food and open bar', 'Premium', 2160, true, 2160, 'charter', 1, 18, true),
  ('Shopping', 'Guided shopping experience', 'Leisure', 20, false, null, 'standard', 1, null, false),
  ('Sightseeing & Shopping', 'Explore and shop Jamaica''s best spots', 'Combined', 50, false, null, 'standard', 1, null, false),
  ('Bob Marley House Tour', 'Historic home of the legendary reggae icon', 'Cultural', 120, false, null, 'standard', 1, null, false),
  ('Bob Marley & Dunn''s River', 'Culture and nature in one unforgettable day', 'Combined', 150, false, null, 'standard', 1, null, false),
  ('Weed Farm & Shopping', 'Unique cultural and agricultural experience', 'Cultural', 60, false, null, 'standard', 1, null, false),
  ('Hiking Experience', 'Trek Jamaica''s lush mountain trails', 'Nature', 70, false, null, 'standard', 4, null, false),
  ('Kingston Highlights', 'Bob Marley Museum, Emancipation Park, Devon House', 'Cultural', 550, true, 550, 'private', 1, 4, false),
  ('Appleton Estate & YS Falls', 'Rum tour and waterfall adventure', 'Combined', 160, false, null, 'standard', 4, null, true),
  ('Appleton Estate Only', 'Historic rum distillery tour', 'Cultural', 120, false, null, 'standard', 1, null, false),
  ('YS Falls Only', 'Majestic waterfall experience', 'Nature', 120, false, null, 'standard', 1, null, false),
  ('Rose Hall Great House Day Tour', 'Historic plantation mansion with legendary tales', 'Cultural', 45, false, null, 'standard', 1, null, false),
  ('Rose Hall Great House Night Tour', 'Evening tour of historic mansion', 'Cultural', 50, false, null, 'standard', 1, null, false),
  ('Rose Hall Great House & Shopping', 'History and shopping experience', 'Combined', 55, false, null, 'standard', 1, null, false),
  ('Dolphin Encounter Lucea', 'Meet and interact with dolphins', 'Marine', 150, false, null, 'standard', 1, null, true),
  ('Dolphin Swim', 'Swim and play with friendly dolphins', 'Marine', 180, false, null, 'standard', 1, null, true),
  ('Dolphin Ultimate Swim', 'Premium dolphin swimming experience', 'Marine', 220, false, null, 'standard', 1, null, true),
  ('Doctor''s Cave Beach', 'Beautiful beach day experience', 'Beach', 20, false, null, 'standard', 4, null, false),
  ('Rockland Bird Sanctuary', 'Bird watching in natural habitat', 'Nature', 73, false, null, 'standard', 4, null, false),
  ('Blue Mountain Tour', 'Hike Jamaica''s most famous mountain peak', 'Nature', 700, true, 700, 'private', 1, 4, false),
  ('Airport Transfer – Montego Bay Hotel', 'Convenient airport transportation', 'Transfers', 40, true, 40, 'private', 1, 4, false),
  ('Airport Transfer – Negril', 'Direct airport to Negril transfer', 'Transfers', 120, true, 120, 'private', 1, 4, false),
  ('Airport Transfer – Ocho Rios', 'Direct airport to Ocho Rios transfer', 'Transfers', 120, true, 120, 'private', 1, 4, false),
  ('Airport Transfer – South Coast', 'Direct airport to South Coast transfer', 'Transfers', 50, false, null, 'standard', 1, null, false)
on conflict do nothing;
